ALTER TABLE audiodemo.phrases ALTER COLUMN id SET GENERATED BY DEFAULT;

INSERT INTO audiodemo.phrases (id, created_at) VALUES
    (1, '2025-01-02 03:04:21.000'),
    (2, '2025-01-02 03:04:22.000'),
    (3, '2025-01-02 03:04:23.000'),
    (4, '2025-01-02 03:04:24.000'),
    (5, '2025-01-02 03:04:25.000'),
    (6, '2025-01-02 03:04:26.000'),
    (7, '2025-01-02 03:04:27.000'),
    (8, '2025-01-02 03:04:28.000'),
    (9, '2025-01-02 03:04:29.000'),
    (10, '2025-01-02 03:04:30.000');

ALTER TABLE audiodemo.phrases ALTER COLUMN id SET GENERATED ALWAYS;

ALTER SEQUENCE audiodemo.phrases_id_seq RESTART WITH 11;
