name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: alpine-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin' # Use Temurin (Adoptium) JDK

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Run tests using Gradle
      - name: Run tests with Gradle
        run: ./gradlew test

      # Optional: Build the project to ensure it compiles
      - name: Build the project
        run: ./gradlew build
